config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/log_out' => 'sessions#destroy', as: 'log_out'

  resources :sessions, only: [:new, :create, :destroy]
  resources :runs, only: [:new, :create]
  resources :users, only: [:new, :create] do
    resources :runs, only: [:new, :create]
  end
end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :user

  validates :ran_on, presence: true
  validates :distance, numericality: { greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  include Authem::User
  has_many :runs, dependent: :destroy

  def current_streak_distance
      calc_unless_no_streak { streaks.first.inject(0.0) { |n, run| n + run.distance } }
  end

  def current_streak_days
    calc_unless_no_streak { streak_length(streaks.first) }
  end

  def current_streak_average
    calc_unless_no_streak { streaks.first.inject(0.0) { |n, run| n + run.distance } / streak_length(streaks.first) }
  end

  def longest_streak
    longest = 0
    streaks.each do |streak|
      new = streak.map { |run| run.ran_on }.uniq.count
      longest = new > longest ? new : longest
    end

    longest
  end

  def streaks
    streak_list = []
    streak = []

    last_date = Date.today
    self.runs.order(ran_on: :desc).each do |run|
      if last_date - run.ran_on > 1
        streak_list << streak
        streak = []
      end

      last_date = run.ran_on
      streak << run
    end

    streak_list << streak

    streak_list
  end

  private

  def streak_length(streak)
    streak.map { |run| run.ran_on }.uniq.count
  end

  def calc_unless_no_streak
    unless streaks.first.empty?
      yield
    else
      0
    end
  end

  def current_streak
    streaks.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  authem_for :user
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_filter :require_user
  expose(:run, attributes: :run_params)
  expose(:new_run) { current_user.runs.build(run_params) }

  def create
    # @run = current_user.runs.build(run_params)

    if new_run.save
      redirect_to :root, notice: "Run successfully added."
    else
      run.valid?
      render :new
    end
  end

  private

  def run_params
    params.require(:run).permit(:ran_on, :distance)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_back_or_to(root_path)
    else
      flash.now.alert = "Your email and password do not match."
      render :new
    end
  end

  def destroy
    sign_out_user
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:users)
  expose(:user)

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to :root, notice: "Account successfully created. Please log in."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Streaky Runner
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .containter-fluid
      .row
        .col-md-3.col-xs-3
        = yield

app/views/runs/new.html.haml
.col-md-3.col-xs-3
  %h2 Log A New Run

  -if !run.errors.nil?
    %ul
    -run.errors.full_messages.each do |error|
      %li= error

  = form_for run do |f|
    .form-group
      =f.label :ran_on
      %br
      =f.date_select :ran_on, class: 'form-control'
    .form-group
      =f.label :distance
      =f.number_field :distance, class: 'form-control'

    =f.submit "Log It", class: 'btn btn-default'

app/views/users/new.html.haml
.col-md-3.col-xs-3
  %h2 New Account

  = form_for user do |f|
    .form-group
      =f.label :email
      =f.text_field :email, class: 'form-control'
    .form-group
      =f.label :password
      =f.password_field :password, class: 'form-control'
    .form-group
      =f.label :password_confirmation
      =f.password_field :password_confirmation, class: 'form-control'
    =f.submit "Sign Up", class: 'btn btn-default'

app/views/welcome/index.html.haml
.col-md-3.col-xs-3
  %h1 Streaky Runner
  -unless current_user
    =link_to "Sign up", new_user_path
    |
    =link_to "Sign in", new_session_path
  -else
    =link_to "Add a new run", new_user_run_path(current_user.id)
    |
    =link_to "Log Out", log_out_path
    %h2 Current Streak
    %p
      Days:
      =current_user.current_streak_days
    %p
      Distance:
      =current_user.current_streak_distance
    %p
      Average Miles Per Day:
      ="%6.2f" % [current_user.current_streak_average]
    %p
      Longest Streak:
      =current_user.longest_streak